---
- name: "(Re)start docker"
  listen: restart docker
  ansible.builtin.systemd:
    name: docker.service
    state: restarted

- name: "(Re)start ECS"
  listen: restart ecs
  ansible.builtin.systemd:
    name: ecs.service
    state: restarted

- name: yum clean metadata
  listen: yum-clean-metadata
  command: yum clean metadata
  args:
    warn: no