version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - export PE_REPO_URL=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - echo "Pulling latest container build (failure ok)..."
      - docker pull $PE_REPO_URL || true
  build:
    commands:
      - echo "Building the Docker image..."
      - docker build --cache-from $PE_REPO_URL -t $IMAGE_REPO_NAME:$IMAGE_TAG $EXTRA_DOCKER_ARGS .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $PE_REPO_URL
  post_build:
    commands:
      - echo "Pushing the Docker image..."
      - docker push $PE_REPO_URL